#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/.."

zip_uri=''
cask_name=''
build_version="0.0.0-SNAPSHOT"
github_repo="ivalkou/rapidkey"

while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        --cask-name) cask_name="$2"; shift 2;;
        --github-repo) github_repo="$2"; shift 2;;
        *) echo "Unknown arg $1" >&2; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" >&2; exit 1; fi
if test -z "$cask_name"; then echo "--cask-name is mandatory" >&2; exit 1; fi

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/RapidKey-tmp.zip
    rm -rf "$zip_file"
    curl -L "$zip_uri" -o "$zip_file"
else
    echo "$zip_uri doesn't exist" >&2
    exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest'
zip_root_dir="RapidKey-v$build_version"
release_url="https://github.com/$github_repo/releases/download/v#{version}/RapidKey-v#{version}.zip"

if ! grep -q SNAPSHOT <<< "$build_version"; then
    cask_version="'$build_version'"
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
fi

rm -f ".release/$cask_name.rb" || true
mkdir -p .release
cat > ".release/$cask_name.rb" <<EOF
cask "$cask_name" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$release_url"
  name "RapidKey"
  desc "Keyboard-driven command palette for macOS"
  homepage "https://github.com/$github_repo"

  depends_on macos: ">= :sequoia" # macOS 15

  postflight do
    system "xattr -d com.apple.quarantine #{appdir}/RapidKey.app"
  end

  app "$zip_root_dir/RapidKey.app"
end
EOF

echo "Generated .release/$cask_name.rb"
